modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="more_everything"
version="1.0.0"
displayName="more everything!"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mark, MCreator"

[[dependencies.more_everything]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




